import { memo } from "react";
import Card from "@/components/ui/Card";
import Button from "@/components/ui/Button";
import {
  CheckCircle2,
  Lightbulb,
  ArrowRight,
  Sparkles,
  Award,
} from "lucide-react";
import type { AnswerEvaluation } from "../types/interview.types";

interface FeedbackCardProps {
  evaluation: AnswerEvaluation;
  onNext: () => void;
  isLastQuestion?: boolean;
  isLoadingNext?: boolean;
}

const FeedbackCard = memo(function FeedbackCard({
  evaluation,
  onNext,
  isLastQuestion = false,
  isLoadingNext = false,
}: FeedbackCardProps) {
  const { score, feedback, strengths, weaknesses, improvements } = evaluation;

  let scoreColor = "bg-emerald-50 text-emerald-700 border-emerald-200";
  if (score < 50) {
    scoreColor = "bg-rose-50 text-rose-700 border-rose-200";
  } else if (score < 75) {
    scoreColor = "bg-amber-50 text-amber-700 border-amber-200";
  }

  return (
    <Card className="p-6 space-y-6 animate-in fade-in zoom-in-95 border-blue-100 shadow-md">
      {/* header with score */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-100 pb-4">
        <div className="flex items-center gap-3">
          <div className="p-2.5 bg-blue-50 text-blue-600 rounded-xl">
            <Sparkles className="w-6 h-6" />
          </div>
          <div>
            <h3 className="text-base font-bold text-slate-900">
              AI Answer Evaluation
            </h3>
            <p className="text-xs text-slate-500">
              Real-time feedback generated by Gemini AI
            </p>
          </div>
        </div>

        <div className={`flex items-center gap-2 px-4 py-2 rounded-xl border font-bold text-sm ${scoreColor}`}>
          <Award className="w-4 h-4" />
          <span>Score: {score}%</span>
        </div>
      </div>

      {/* general feedback summary */}
      {feedback && (
        <div className="p-4 bg-slate-50 rounded-xl border border-slate-200 text-xs text-slate-700 leading-relaxed">
          {feedback}
        </div>
      )}

      {/* strengths & improvements */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* strengths */}
        {strengths && strengths.length > 0 && (
          <div className="p-4 bg-emerald-50/50 rounded-xl border border-emerald-100 space-y-2">
            <h4 className="text-xs font-bold text-emerald-800 uppercase tracking-wider flex items-center gap-1.5">
              <CheckCircle2 className="w-4 h-4 text-emerald-600" />
              Key Strengths
            </h4>
            <ul className="space-y-1.5">
              {strengths.map((item, idx) => (
                <li key={idx} className="text-xs text-emerald-900 flex items-start gap-1.5">
                  <span className="text-emerald-500 font-bold">•</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* improvements */}
        {((improvements && improvements.length > 0) || (weaknesses && weaknesses.length > 0)) && (
          <div className="p-4 bg-amber-50/50 rounded-xl border border-amber-100 space-y-2">
            <h4 className="text-xs font-bold text-amber-800 uppercase tracking-wider flex items-center gap-1.5">
              <Lightbulb className="w-4 h-4 text-amber-600" />
              Areas for Improvement
            </h4>
            <ul className="space-y-1.5">
              {(improvements || weaknesses).map((item, idx) => (
                <li key={idx} className="text-xs text-amber-900 flex items-start gap-1.5">
                  <span className="text-amber-500 font-bold">•</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>

      {/* next question action button */}
      <div className="flex justify-end pt-2">
        <Button
          onClick={onNext}
          isLoading={isLoadingNext}
          loadingText={isLastQuestion ? "Generating report..." : "Loading next question..."}
          className="flex items-center gap-2 px-6"
        >
          <span>{isLastQuestion ? "Finish Interview & View Report" : "Continue to Next Question"}</span>
          <ArrowRight className="w-4 h-4" />
        </Button>
      </div>
    </Card>
  );
});

export default FeedbackCard;
